<a href="https://colab.research.google.com/github/Chriss060529/data_science_w1/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

q1 = np.array([[1,2],[3,4]])
print(q1)

[[1 2]
 [3 4]]


In [8]:
q2 = np.random.random((3,4))
print(q2)

[[0.46846721 0.01039148 0.09553329 0.4930502 ]
 [0.73601455 0.64215727 0.83865522 0.18590472]
 [0.10511866 0.93818839 0.98698076 0.13724983]]


In [10]:
q3_ones = np.ones((2,3))
q3_zeros = np.zeros((2,3))

print(q3_ones)
print(q3_zeros)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
q4 = np.random.random((6,3))
print(q4)

q4_transpose = q4.T
print(q4_transpose)

[[0.86573266 0.11448271 0.43536759]
 [0.92504129 0.50283757 0.86426156]
 [0.74591409 0.42434673 0.3079571 ]
 [0.88874421 0.65750421 0.80562148]
 [0.81503787 0.47703835 0.127667  ]
 [0.90706724 0.9461029  0.76527655]]
[[0.86573266 0.92504129 0.74591409 0.88874421 0.81503787 0.90706724]
 [0.11448271 0.50283757 0.42434673 0.65750421 0.47703835 0.9461029 ]
 [0.43536759 0.86426156 0.3079571  0.80562148 0.127667   0.76527655]]


In [18]:
q5a = np.random.random((2,3))
q5b = np.random.random((3,1))

print(q5a)
print(q5b)

q5_dot = np.dot(q5a, q5b)
print(q5_dot)

[[0.76610453 0.63402475 0.73837809]
 [0.55643638 0.23312747 0.65841255]]
[[0.60754111]
 [0.26632542]
 [0.88489322]]
[[1.28768267]
 [0.98277054]]
